export function generateName(wordNumber: number, divider = " "): string {
    const allOptions = source.join(" ");
    const singleWords = allOptions.split(" ");

    const names = [];
    while (names.length < wordNumber) {
        const random = randomFrom(singleWords);
        const capped = random.substr(0, 1).toUpperCase() + random.substr(1);
        names.push(capped);
    }

    return names.join(divider);
}

function randomFrom(collection) {
    return collection[Math.floor(Math.random() * collection.length) + 0];
}

const source = [


    "Candy cane",
    "Bell",
    "Bauble",
    "Christmas ornament",
    "Candle",
    "Bow",
    "Holly",
    "Gift",
    "Poinsettia",
    "Wreath",
    "Garland",
    "Light",
    "Candy",
    "Stockings",
    "Gingerbread man",
    "Snow globe",
    "Christmas tree",
    "Christmas pudding",
    "Santa’s hat",
    "Fireplace",
    "Gingerbread house",
    "Santa Claus",
    "Elf",
    "Snowman",
    "Sleigh",
    "Reindeer",
    "Santa’s sack",
    "Christmas card",
    "Chimney",
    "Menorah",
    "Snowflake",

    "Advent",
    "Angels",
    "Announcement",
    "Bells",
    "Bethlehem",
    "Blitzen",
    "Candles",
    "Candy",
    "Candy canes",
    "Cards",
    "Cedar",
    "Celebrate",
    "Ceremonies",
    "Chimney",
    "Christmas cookies",
    "Christmas tree",
    "Cold",
    "Comet",
    "Cranberry sauce",
    "Crowds",
    "Cupid",
    "Dancer",
    "Dasher",
    "December",
    "Decorations",
    "Dolls",
    "Donner",
    "Dressing",
    "Eggnog",
    "Elves",
    "Family reunion",
    "Festival",
    "Fir",
    "Frosty",
    "Fruitcake",
    "Gift boxes",
    "Gifts",
    "Goodwill",
    "Greetings",
    "Ham",
    "Happy",
    "Holiday",
    "Holly",
    "Holy",
    "Icicles",
    "Jolly",
    "Lights",
    "Lists",
    "Merry",
    "Miracle",
    "Mistletoe",
    "New Year",
    "Noel",
    "North Pole",
    "Pageant",
    "Parades",
    "Party",
    "Pie",
    "Pine",
    "Plum pudding",
    "Poinsettia",
    "Prancer",
    "Presents",
    "Pumpkin pie",
    "Punch",
    "Red",
    "green",
    "Reindeer",
    "Ribbon",
    "Rudolph",
    "Sacred",
    "Sales",
    "Sauce",
    "Scrooge",
    "Season",
    "Sled",
    "Sleighbells",
    "Snowflakes",
    "Spirit",
    "St. Nick",
    "Stand",
    "Star",
    "Stickers",
    "Stocking stuffers",
    "Sweet potato",
    "Tidings",
    "Tinsel",
    "Togetherness",
    "Toys",
    "Tradition",
    "Traffic",
    "Trips",
    "Turkey",
    "Vacation",
    "Vixen",
    "Winter",
    "Worship",
    "Wrapping paper",
    "Wreath",
    "Yule",
    "Yuletide",

    "Adeste",
    "Fideles",
    "Advent",
    "Angel",
    "Appreciation",
    "Aroma",
    "Artificial tree",
    "Assemble",
    "Awe",
    "Baking",
    "Balsam",
    "Beauty",
    "Bells",
    "Belonging",
    "Bethlehem",
    "Birth",
    "Blessings",
    "Blitzen",
    "Boughs",
    "Bows",
    "Boxes",
    "Boxing Day",
    "Camels",
    "Candles",
    "Candy canes",
    "Cards",
    "Caring",
    "Caroler",
    "Carols",
    "Carve",
    "Catalyst",
    "Celebrate",
    "Celebration",
    "Ceremony",
    "Charity",
    "Child",
    "Children",
    "Chimney",
    "Chocolate",
    "Christmas",
    "Christmas cookies",
    "Christmas Eve",
    "Christmas past",
    "Christmas future",
    "Church",
    "Cloves",
    "Coal",
    "Comet",
    "Comfort",
    "Communication",
    "Community",
    "Companionship",
    "Cornucopia",
    "Cranberries",
    "Creche",
    "Crowds",
    "Dancer",
    "Dancing",
    "Dasher",
    "December",
    "Decoration",
    "Dolls",
    "Donations",
    "Donner",
    "Dreidel",
    "Duck",
    "Ebenezer Scrooge",
    "Efforts",
    "Eggnog",
    "Elves",
    "Embrace",
    "Emmanuel",
    "Entertain",
    "Entertainment",
    "Epiphany",
    "Eve",
    "Evergreens",
    "Exchange",
    "Expectations",
    "Expensive",
    "Faith",
    "Familiar",
    "Family",
    "Father Christmas",
    "Feast",
    "Fervor",
    "Festival",
    "Festive",
    "Fireplace",
    "Flat-bread",
    "Forgiveness",
    "Frankincense",
    "Freedom",
    "Friends",
    "Friendship",
    "Frosty the Snowman",
    "Fruitcake",
    "Garland",
    "Gather",
    "Gathering",
    "Generations",
    "Ghost of Christmas past",
    "Gifts",
    "Gingerbread",
    "Gold",
    "Goodwill",
    "Goose",
    "Gourmet",
    "Grace",
    "Gratitude",
    "Gravy",
    "Greenery",
    "Greens",
    "Greetings",
    "Grinch",
    "Groups",
    "Guests",
    "Ham",
    "Hanukkah",
    "Hard sauce",
    "Harvest",
    "Heart",
    "Heartland",
    "Heavenly",
    "Heritage",
    "Holding hands",
    "Holiday",
    "Holly",
    "Holy",
    "Home",
    "Homeward",
    "Hope",
    "Host",
    "Hostess",
    "Hugs",
    "Humility",
    "Hymns",
    "Icicles",
    "Illumination",
    "Infant",
    "Inn",
    "Innocence",
    "Invitations",
    "Ivy",
    "Jack Frost",
    "Jack-in-the-box",
    "Jingle bells",
    "Jolly",
    "Journey",
    "Joy",
    "Joyful",
    "Karamu",
    "Kibbe",
    "Kinara",
    "King Wenselaus",
    "Kisses",
    "Kris Kringle",
    "Kwanzaa",
    "Laughter",
    "Lighting",
    "Lights",
    "Lists",
    "Little Drummer Boy",
    "Love",
    "Magi",
    "Mail",
    "Majesty",
    "Manger",
    "Mantle",
    "Meat and spices",
    "Memories",
    "Menorah",
    "Merry",
    "Messages",
    "Midnight",
    "Mincemeat",
    "Minister",
    "Miracle",
    "Miraculous",
    "Mistletoe",
    "Mittens",
    "Mosque",
    "Mrs Claus",
    "Music",
    "Music box",
    "Myrrh",
    "Myths",
    "Nativity",
    "Network",
    "Nocturnal",
    "Noel",
    "North Pole",
    "Nostalgia",
    "Nutcrackers",
    "Nutmeg",
    "Nuts",
    "Observance",
    "Occasion",
    "Ornament",
    "Packages",
    "Pageant",
    "Pageantry",
    "Parade",
    "Partridge",
    "Party",
    "Patriotism",
    "Peace",
    "Phone calls",
    "Pies",
    "Pixie",
    "Plum pudding",
    "Poinsettia",
    "Popcorn string",
    "Post office",
    "Prancer",
    "Prayer",
    "Presents",
    "Pride",
    "Priest",
    "Priorities",
    "Proclaim",
    "Program",
    "Pumpkin pie",
    "Punch",
    "Quality",
    "Quantity",
    "Questions",
    "Quince pie",
    "Quirky",
    "Reconciliation",
    "Reflection",
    "Refuge",
    "Reindeer",
    "Rejoice",
    "Relationship",
    "Relatives",
    "Reminiscence",
    "Resolutions",
    "Reunions",
    "Reveal",
    "Revel",
    "Reverence",
    "Ribbons",
    "Ritual",
    "Rooftop",
    "Roots",
    "Rudolph",
    "Sack",
    "Saint Nicholas",
    "Sanctuary",
    "Santa Claus",
    "Sauce",
    "Scents",
    "Scrooge",
    "Scrumptious",
    "Season",
    "Secular",
    "Sending",
    "Sharing",
    "Shepherd",
    "Shock",
    "Shopping",
    "Silver bells",
    "Sled",
    "Sleigh",
    "Sleigh bells",
    "Snow",
    "Snowman",
    "Songs",
    "Spices",
    "Spirit",
    "Stable",
    "Stand",
    "Star",
    "Stocking stuffer",
    "Stockings",
    "Stress",
    "Stuffing",
    "Sugar plums",
    "Sundown",
    "Surprises",
    "Sustenance",
    "Symbol",
    "Symbolism",
    "Synagogue",
    "Teddy bear",
    "Temple",
    "Tenderness",
    "Tension",
    "Texts",
    "Thankful",
    "Thanks",
    "The Nutcracker Ballet",
    "Three Kings",
    "Tidings",
    "Tinkling",
    "Tinsel",
    "Tiny Tim",
    "Toboggan",
    "Toys",
    "Tradition",
    "Train",
    "Tranquility",
    "Travel",
    "Tree",
    "Trimmings",
    "Trips",
    "Trust",
    "Tug",
    "Turkey",
    "Twinkling",
    "Typical",
    "Understanding",
    "Unify",
    "Universal",
    "Unwrap",
    "Vacation",
    "Values",
    "Vanilla",
    "Venison",
    "Vixen",
    "Volunteer",
    "Walnuts",
    "Wassail",
    "Wenceslaus",
    "Whimsy",
    "Winter",
    "Wise Men",
    "Wishes",
    "Wonder",
    "Wonderland",
    "Workshop",
    "Worship",
    "Worshiper",
    "Wrapping",
    "Wreath",
    "Xmas",
    "Youth",
    "Yule log",
    "Yuletide",
    "Zesty",
];